### ISSUE TITLE
The plugin no longer works in Binary Ninja 1.2.1921

### ISSUE THREAD

**Issue by bmuessig** [orndorffgrant/bnhook#2]
The following error message is displayed on load:
```
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Roaming\Binary Ninja\plugins\bnhook\__init__.py", line 5, in <module>
    from .hookmanager import hook_manager_create
  File "C:\Users\Benedikt\AppData\Roaming\Binary Ninja\plugins\bnhook\hookmanager.py", line 4, in <module>
    from filebytes.elf import ELF, PT, PF
ImportError: No module named filebytes.elf
Python plugin 'bnhook' could not be loaded
```

**Comment by bmuessig** [comment]
I might have overread the plugin requirements. I will try installing the dependencies.
